# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test test_env.py'
        - PYTHON_VERSION=3.5
        - DEBUG=True

    matrix:
        - SETUP_CMD='egg_info'
          TEST_CMD='python --version'

        - SETUP_CMD='test'

matrix:
    include:

        - os: linux
          env: SETUP_CMD='test --open-files'

        - os: linux
          env: SETUP_CMD='test --coverage' PYTHON_VERSION=2.7
               TEST_CMD='coverage run test_env.py'
               CONDA_CHANNELS='astropy-ci-extras astrofrog conda-forge'
               CONDA_DEPENDENCIES='pyqt5' DEBUG=True
               NUMPY_VERSION=1.10 ASTROPY_VERSION=lts


before_install:
    - ln -s . ci-helpers
    - source ci-helpers/travis/setup_conda.sh

script:
   - eval $TEST_CMD
   - if [[ $SETUP_CMD == *coverage* ]]; then coveralls; fi
